### ISSUE TITLE
Inefficient Use of `strcmp()`

### ISSUE THREAD

**Issue by gilarellano** [gilarellano/woodwindow-quoting-software#2]
`strcmp()` is repeatedly used to compare strings in the `WoodWindow.cpp` `CalculateCost()` function. This could be made more efficient and readable by using C++ string comparisons, or by storing window properties as enums or constants instead of strings.

**Comment by Itachi0906** [comment]
Hey @gilarellano , I had a doubt can't we just directly compare the two strings directly using == operator rather than using strcmp() to compare them or without storing them anything
